# ==============================================================================
# Modern E-Commerce Data Lakehouse Platform
# Trino Worker Server Configuration
# ==============================================================================
coordinator=false
http-server.http.port=8085
query.max-memory=4GB
query.max-memory-per-node=1GB
query.max-total-memory-per-node=2GB
discovery.uri=http://trino-coordinator:8085
